steps:
  - name: Generate stats
    image: python
    secrets: [ access_token, user, git_url ]
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - USER=${USER}
      - GIT_URL=${GIT_URL}
    when:
      - event: manual
      - event: cron
    commands:
      - python -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - python main.py
  - name: Commit to the repo
    image: alpine
    secrets: [ commit_token ]
    when:
      - event: manual
      - event: cron
    commands:
      - apk add git
      - git config --global user.name "[CI] Stats generator"
      - git config --global user.email ${USER}"@noreply.codeberg.org"
      - git remote remove origin
      - git remote add origin "https://"${COMMIT_TOKEN}"@codeberg.org/"${USER}"/forgejo-stats.git"
      - git add .
      - git commit -m "[CI] Update stats ($( env TZ=Europe/Berlin date +"%d.%m.%Y %H:%M" )) [SKIP CI]"
      - git push --set-upstream origin main
