steps:
  - name: Generate stats
    image: python
    secrets: [ access_token, user, git_url ]
    environment:
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - USER=${USER}
      - GIT_URL=${GIT_URL}
    commands:
      - python -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements.txt
      - python3 main.py
  - name: Commit to the repo
    image: debian
    commands:
      - git config --global user.name "CI Stats generator"
      - git config --global user.email "tuxilio@noreply.codeberg.org"
      - git add .
      - git commit -m '[CI] Update stats'
      - git push